[workspace]
authors = ["Jackson Kunde <jacksonkunde@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "gpu-intro"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
mojo = ">=0.25.7.0.dev2025110818,<0.26"
numpy = ">=2.3.5,<3"
max = ">=25.7.0.dev2025111305,<26"
scipy = ">=1.16.3,<2"
